variables:
  POSTGRES_HOST_AUTH_METHOD: trust


before_script:
  - mkdir -p ~/.config/pip
  - ./setup.bash
  - source venv/bin/activate
  - python -V

test:1804:
  image: code.chs.usgs.gov:5001/asl/asl-main/asl:1804
  services:
    - postgres:12.2-alpine
  script:
    - source venv/bin/activate
    - python manage.py test --settings asldqaweb.settings_ci

test:latest:
  image: code.chs.usgs.gov:5001/asl/asl-main/asl:latest
  services:
    - postgres:latest
  script:
    - source venv/bin/activate
    - python manage.py test --settings asldqaweb.settings_ci

test:safety:
  image: code.chs.usgs.gov:5001/asl/asl-main/asl:1804
  
  script:
    - source venv/bin/activate
    - pip freeze > pip_freeze.txt
    - deactivate
    # Need to install outside the venv to prevent this install patching actual issues.
    - pip install --upgrade requests
    - pip install --upgrade safety
    # Fix certifi certs so updated insecurity DB can be downloaded.
    - /bin/virtualenv_certifi_fix_for_select_situations.bash
    - safety check -r pip_freeze.txt
