# Generated by Django 3.2.8 on 2021-11-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='date_format',
            field=models.CharField(default='yy-mm-dd', max_length=10, verbose_name='DateFormat'),
        ),
    ]
