# Generated by Django 3.2.8 on 2021-11-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_alter_custom_date_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='units',
            field=models.CharField(blank=True, max_length=64, verbose_name='Units'),
        ),
    ]
