# Generated by Django 3.2.8 on 2022-02-11 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_metricunits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='channel_filter',
            field=models.TextField(help_text='Limit scan to this channel', verbose_name='Channel Filter'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='delete_existing',
            field=models.BooleanField(default=False, help_text='Flag to delete existing scan data as you scan', verbose_name='Delete Exisiting'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='end_date',
            field=models.DateField(help_text='Scan ends on this date', verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='finished',
            field=models.BooleanField(default=False, help_text='Scan of this entry is finished', verbose_name='Scan Finished'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last time this scan was modified', verbose_name='Last Update'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='location_filter',
            field=models.TextField(help_text='Limit scan to this location', verbose_name='Location Filter'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='metric_filter',
            field=models.TextField(help_text='Limit scan to this metric', verbose_name='Metric Filter'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='network_filter',
            field=models.TextField(help_text='Limit scan to this network', verbose_name='Network Filter'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='parent',
            field=models.ForeignKey(help_text='None indicates root level, otherwise points to parent scan', on_delete=django.db.models.deletion.DO_NOTHING, to='metrics.scan'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='priority',
            field=models.IntegerField(default=10, help_text='Scan priority, 100 highest. 0 forget it', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scheduled_run',
            field=models.DateField(help_text='Run scan in the future after this date', verbose_name='Scheduled Run Date'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='start_date',
            field=models.DateField(help_text='Scan starting at this date', verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='station_filter',
            field=models.TextField(help_text='Limit scan to this station', verbose_name='Station Filter'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='taken',
            field=models.BooleanField(default=False, help_text='Scan of this entry is in progress, scan engine uses multi-threading', verbose_name='Scan Taken'),
        ),
        migrations.AlterField(
            model_name='scanmessage',
            name='channel',
            field=models.CharField(help_text='channel', max_length=10, verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='scanmessage',
            name='location',
            field=models.CharField(help_text='location', max_length=10, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='scanmessage',
            name='message',
            field=models.TextField(help_text='Actual message', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='scanmessage',
            name='metric',
            field=models.CharField(help_text='metric', max_length=50, verbose_name='Metric'),
        ),
        migrations.AlterField(
            model_name='scanmessage',
            name='network',
            field=models.CharField(help_text='network', max_length=2, verbose_name='Network'),
        ),
        migrations.AlterField(
            model_name='scanmessage',
            name='scan',
            field=models.ForeignKey(help_text='scan message applies to', on_delete=django.db.models.deletion.DO_NOTHING, to='metrics.scan'),
        ),
        migrations.AlterField(
            model_name='scanmessage',
            name='station',
            field=models.CharField(help_text='station', max_length=10, verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='scanmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp for message creation', verbose_name='Timestamp'),
        ),
    ]
